AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: bolt-js-sam-demo

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  BoltJsSamDemo:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        SlackEvent:
          Type: Api
          Properties:
            Path: /slack/event
            Method: post
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: '{{resolve:secretsmanager:slack-tokens-and-secrets:SecretString:SLACK_SIGNING_SECRET}}'
          SLACK_BOT_TOKEN: '{{resolve:secretsmanager:slack-tokens-and-secrets:SecretString:SLACK_BOT_TOKEN}}'
    Metadata:
      DockerTag: nodejs18.x-v1
      DockerContext: ./
      Dockerfile: Dockerfile

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  BoltJsSamDemoApi:
    Description: API Gateway endpoint URL for BoltJsSamDemo
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/slack/event"

  AwsLambdaNodeJsDemoBoltJsSamDemo:
    Description: Lambda Function ARN
    Value: !GetAtt BoltJsSamDemo.Arn

  BoltJsSamDemoIamRole:
    Description: Implicit IAM Role created for BoltJsSamDemo
    Value: !GetAtt BoltJsSamDemoRole.Arn
