name: 'Release'

on:
  workflow_dispatch:

jobs:
  release:
    uses: ./.github/workflows/_build_and_deploy.yaml
    permissions:
      id-token: write
      contents: read
    with:
      role: 'arn:aws:iam::735467579431:role/github-actions'
